### ISSUE TITLE
[Issue] A single radio program is on air for 24 hours

### ISSUE THREAD

**Issue by ExperiencersInternational** [dp247/Freeview-EPG#13]
Well ermm yeah. Self-explanatory.

BBC must be hiring some great people for a show to last that long.

![Screenshot_2023-04-29-16-44-53-064_com cosmiquest tv](https://user-images.githubusercontent.com/56035537/235311363-8bce55bf-b6f9-4405-a6f2-1ad54c3f26da.jpg)
![Screenshot_2023-04-29-16-44-34-957_com cosmiquest tv](https://user-images.githubusercontent.com/56035537/235311364-3285355c-0e06-4f67-8c25-d684f3b083ab.jpg)

I think my application doesn't trigger security restrictions if I'm watching radio which is good to know.

**Comment by dp247** [comment]
This isn't something I'll probably be able to fix right now (or without a large rewrite of the scraper) - its down to BBC Sounds not having a 'Late' category for the station on that day (so the scraper makes the end time the day after, but doesn't have a late section to get the next time from). I'll bump the Github Action to generate an EPG every 8 hours though, so things like this won't stick around for long
