### ISSUE TITLE
[Channel request] Various 27x and 28x Freeview channels

### ISSUE THREAD

**Issue by ExperiencersInternational** [dp247/Freeview-EPG#14]
**Information**
|Channel name|Freeview channel number|EPG ID|
|Al Jazeera Arabic|286|AlJazeeraArabic.qa|
|WION|287|WION.in|
|Al Arabiya|273|AlArabiya.uk|
|Asharq News|272|AsharqNews.uk|

the EPG IDs I've assigned are likely not the ones that IPTV-org uses, but I was unable to find any EPG IDs for them here

---

unrelated but your GitHub actions output is unreadable for radio, idk why

![Screenshot_2023-04-30-22-03-40-622_com microsoft emmx](https://user-images.githubusercontent.com/56035537/235376215-1a894bfc-b0e9-4fff-9a45-ac30295953d3.jpg)

also, the RT UK EPG has been broken for a while, likely due to Ofcom withdrawing it from being broadcast due to being Russian state media last year

**Comment by dp247** [comment]
> the EPG IDs I've assigned are likely not the ones that IPTV-org uses, but I was unable to find any EPG IDs for them here

Only WION is on Sky, but I added it in

> unrelated but your GitHub actions output is unreadable for radio, idk why

Yeah, I didn't expect anyone to read the actions output, so I left a lot of Python debug prints in 🤣 .

> the RT UK EPG has been broken for a while

IIRC, its the English stream from RT's website, so data won't be in this repo
