### ISSUE TITLE
[Issue] BBC Regional Channels don't work

### ISSUE THREAD

**Issue by ExperiencersInternational** [dp247/Freeview-EPG#15]
**Describe the issue**
BBC One Regional Channels EPG doesn't work on https://github.com/ExperiencersInternational/tvsetup, despite being scanned in.

also, it doesn't look like GitHub actions are working properly on the EPG, some refreshes are being skipped

**Screenshots**
![Screenshot_2023-06-26-19-23-52-419_com microsoft emmx](https://github.com/dp247/Freeview-EPG/assets/56035537/5d9191cc-46eb-47ad-b7df-727028d56155)
![Screenshot_2023-06-26-19-21-19-170_com microsoft emmx](https://github.com/dp247/Freeview-EPG/assets/56035537/7b95f57b-b6f0-43ac-8958-653a6d303617)

Can't show screenshot of EPG in application due to Android security restrictions.

**Device information**
Xiaomi POCO X3 Pro, 6GB RAM, 128GB storage, Android 13
Toshiba 43QA5D63DB, 2GB RAM, 8GB storage, Android 11

Using CosmiTV player app

**Comment by dp247** [comment]
I imagine the channels ids probably changed in the HD switchover, so if I find them out, I'll change them

**Comment by ExperiencersInternational** [comment]
> I imagine the channels ids probably changed in the HD switchover, so if I find them out, I'll change them

Yeah would make sense

I literally have no idea where to find the channel IDs so I can't really help

**Comment by dp247** [comment]
I believe it's here:
https://epgservices.sky.com/5.1.1/api/2.1/region/json/4097/1/

**Comment by dp247** [comment]
#16 fixes this
