### ISSUE TITLE
Add a +1 timeshift for STV

### ISSUE THREAD

**Issue by ExperiencersInternational** [dp247/Freeview-EPG#2]
There is a listing for regular STV but for whatever reason there's not a +1 timeshift EPG.

I'm pretty sure it was the same with the Sky EPG on IPTV-org/epg.

**Comment by dp247** [comment]
Nope, this data is wrong lol

**Comment by dp247** [comment]
@ExperiencersInternational I think the latest EPG file should have this in (and working)
![image](https://user-images.githubusercontent.com/9065463/232561251-5d12faed-09e0-4ced-91dd-9f94be876414.png)

**Comment by ExperiencersInternational** [comment]
Confirmed. Currently working on finishing all the local radio stations on the playlist.

**Comment by dp247** [comment]
> Confirmed. Currently working on finishing all the local radio stations on the playlist.

Nice! Feel free to ping me on Discord if you'd rather chat there! Mine is 6767#7676

**Comment by ExperiencersInternational** [comment]
I don't have it lol, I'm sure a lot of people must think that I'm strange for using Mastodon instead of Twitter or anything else, and not using Discord
