### ISSUE TITLE
[Channel request] Missing BBC One London

### ISSUE THREAD

**Issue by ExperiencersInternational** [dp247/Freeview-EPG#21]
**Information**
Channel name: BBC One London
Channel website: no im not filling this out
Any other info (e.g. EPG ID or number): idk

all i know is its missing, have no idea whether anything else is missing

**Comment by ExperiencersInternational** [comment]
also ideal world went bankrupt so you may as well remove that, although it doesn't harm anyone?

https://idealworld.tv

![image](https://github.com/dp247/Freeview-EPG/assets/56035537/1e6154b0-ad92-4ab7-9859-243c5a47af56)

**Comment by dp247** [comment]
> also ideal world went bankrupt so you may as well remove that, although it doesn't really harm anyone?
> 
> https://idealworld.tv
> 
> ![image](https://user-images.githubusercontent.com/56035537/253684412-1e6154b0-ad92-4ab7-9859-243c5a47af56.png)

never did see the point in that channel lmao.

also should be added in [c95f944](https://github.com/dp247/Freeview-EPG/commit/c95f9447af284cd3d9321ea3cedefeb3bfca14fe) :)
