### ISSUE TITLE
[Channel request] ITV 1 Regions

### ISSUE THREAD

**Issue by a13xmay** [dp247/Freeview-EPG#23]
**Information**
Channel name: ITV1
Channel website: itv.com
Any other info (e.g. EPG ID or number): ITV regions from Sky guide - Border/Mids/Meridians/Yorkshire etc?

**Comment by dp247** [comment]
Added most of these that I could find. If you need a specific region, lemme know.

**Comment by a13xmay** [comment]
Meridian South East please. Thanks for this it’s excellent.
