### ISSUE TITLE
Feature request: More days on EPG

### ISSUE THREAD

**Issue by amsound** [dp247/Freeview-EPG#24]
Hi, is it possible to have more than 2 days of data? 5-7 would be ideal.

**Comment by dp247** [comment]
It's probably technically possible. I haven't made it longer since the repo relies on Github actions and already takes up to 6 minutes per run for 48 hours, and the file size is already pretty big for and XML guide.

**Comment by amsound** [comment]
Perhaps you could you provide instructions for  for this to be run locally where days could be tweaked meaning the size/time of the processing/file is less of an issue?

**Comment by xoceunder** [comment]
This timezone

**Comment by amsound** [comment]
Any update on this at all? Thanks so much

**Comment by dp247** [comment]
It'll need some rewriting to generate more than 48 hours. I was planning to make it a parameter thing (like number of days), but I don't have time to do it right now. It'll probably get it's own branch for standalone use when I do, so people get a choice to have the 48 guide generated for them, or one they can run themselves 😊

**Comment by amsound** [comment]
That would be super. Thanks for taking the time, when you can, to take a look. I will keep an eye out on your repository.

**Comment by dp247** [comment]
I've created a branch to work on this [here](https://github.com/dp247/Freeview-EPG/tree/custom). It will need some testing, but its a start :)
