### ISSUE TITLE
[Channel request] BBC Radio Somerset

### ISSUE THREAD

**Issue by danbracey** [dp247/Freeview-EPG#25]
**Information**
Channel name: BBC Radio Somerset
Channel website: https://www.bbc.co.uk/sounds/play/live:bbc_radio_somerset_sound
Any other info (e.g. EPG ID or number): Scheduling website - https://www.bbc.co.uk/sounds/schedules/bbc_radio_somerset_sound#on-air

**Comment by dp247** [comment]
Hey @danbracey,
Would you mind retrieving your Freeview network ID for me, please?
I should add instructions to the readme, but to do it, just go to the [Freeview TV Guide](https://www.freeview.co.uk/tv-guide) and the URL should change to have some numbers in front of it (like `userNid=64257`). Just paste those here and I can get moving :)

**Comment by danbracey** [comment]
> Hey @danbracey,
> Would you mind retrieving your Freeview network ID for me, please?
> I should add instructions to the readme, but to do it, just go to the [Freeview TV Guide](https://www.freeview.co.uk/tv-guide) and the URL should change to have some numbers in front of it (like `userNid=64257`). Just paste those here and I can get moving :) 

Many thanks for your quick reply, it is indeed 64257, https://www.freeview.co.uk/tv-guide?userNid=64257

I can't seem to find a login to get a personalised number, so hope this is OK!

**Comment by dp247** [comment]
Added to the channel list, so should be in the next EPG :)
