### ISSUE TITLE
[Channel request]

### ISSUE THREAD

**Issue by gwinkless** [dp247/Freeview-EPG#29]
Please fill in the table:
> Note: If you're requesting a radio channel and/or a channel that airs on Freeview, please include your postcode in the additional information section.

|                                                       | Response              |
|--------------------------------------|-----------------------|
| Channel name                                | ITVBe +1    |
| Is the channel free-to-air?              | Yes              |
| Does the channel have a website? | itv.com |
| Enter any additional information   | https://www.freeview.co.uk/get-freeview-play/channels/itvbe1    |

There's suggestions that it used to be aired for limited times but it seems to be on all the time now, at least here in NG17.

**Comment by dp247** [comment]
Should be in the next run :3

**Comment by dp247** [comment]
Also a word on this, the +1 titles are different since the channel isn't on Sky, so it uses Freeview. If its an issue, I can get both from Freeview, just lmk.
