### ISSUE TITLE
EPG Unable to be displayed via Kodi PVR

### ISSUE THREAD

**Issue by Sharkeology** [dp247/Freeview-EPG#30]
**Describe the issue**
I'm finding that the EPG is not being filled out by the IPTV Simple Client addon in Kodi, despite the xmltv file being pointed to in the settings.

**Expected behavior**
The EPG should appear showing the names and details of programs as part of the .

**Screenshots**
Screenshots have been attached to this issue to show the contents of the EPG as well as the appropriate file being pointed to for the XMLTV URL.

![kodi_ZCmerI4IB1](https://github.com/dp247/Freeview-EPG/assets/112336841/18132850-fefa-4c88-91f0-d790d57e29a7)
![kodi_wbKGhKioaL](https://github.com/dp247/Freeview-EPG/assets/112336841/5663004a-a68d-4089-bae3-16bc6d25bcf0)

**Device information**
AMD Ryzen 5 3600 desktop running Kodi 20.2 under Windows 10
i5 4570-T Mini PC running Kodi 20.2 under Batocera 38 (Linux).

**Additional context**

**Comment by dp247** [comment]
Can you attach a full debug log from Kodi please? I'll have a look at see what's going on 😊

**Comment by Sharkeology** [comment]
I apologise, that's something I should have done initially.

I've attached the entire file to this post but I think that this error may be the culprit:
`2023-11-30 11:08:52.485 T:3804    error <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - iptvsimple::Epg::LoadEPG - Unable parse EPG XML: Start-end tags mismatch, offset: 120: 
                                                   [ 
                                                       <icon src="https://raw.githubusercontent.com/tv-logo/tv-logos/main/countries/united-kingdom/5-action-uk.png"/>
                                                     </channel> 
                                                   ]`

[kodi.log](https://github.com/dp247/Freeview-EPG/files/13511985/kodi.log)

**Comment by dp247** [comment]
Ah, I think I know the issue - think its expecting:
```xml
  <channel id="5Star.uk">
    <display-name lang="en">5 Star</display-name>
    <icon src="https://i.imgur.com/PI11s9s.png"></icon>
  </channel>
```

However, the way the XML is written is the same as the [XMLTV format guide](https://wiki.xmltv.org/index.php/XMLTVFormat)

**Comment by dp247** [comment]
I can always try generate a file that does include the end tags, if you want to still use the addon.

**Comment by Sharkeology** [comment]
As far as I've seen it's the only .m3u/xmltv based IPTV solution that people use regarding Kodi unfortunately, so if it's at all possible I think that it might be appreciated by others who use it as well.

**Comment by Sharkeology** [comment]
Any luck on this? I checked it with Jellyfin and the EPG seemed to appear just fine but I know that's a completely separate project to Plex.

**Comment by dp247** [comment]
I haven't had time to look yet, sorry 😓

**Comment by dp247** [comment]
Quick update - this got tied in with converting the channel data from XML to JSON. So it is coming (and looks to be working lol). Should be in `main` by the weekend if not before.

**Comment by dp247** [comment]
<img src="https://media2.giphy.com/media/fOzVB89gnznJXaZ1Ti/giphy.gif"/>
