### ISSUE TITLE
No "New" indicator and season/episode information

### ISSUE THREAD

**Issue by gwinkless** [dp247/Freeview-EPG#31]
**Describe the issue**
Episodes of a multi-part show have Incorrect season and episode values, also the "New" indicator is not set.

**Expected behavior**
Episode and season values to be filled in, NEW indicator on new shows.

**Additional context**
I can see that the Sky EPG API does not return "new" flags or season/episode values.

https://github.com/steventrux/epg/blob/master/uk-sky.com.ini uses an approach of extracting the premiere and episode information from the description string, which while not ideal is more workable than not having any at all. Could this be added? If you don't have the time or inclination would you be likely to accept a pull request if I were to do it?

Thanks!

**Comment by dp247** [comment]
I probably won't do it, but feel free to submit a PR 😊

**Comment by gwinkless** [comment]
I went ahead with this, and found the best way to grab this data was to use the awk EPG at awk.epgsky.com since that has "new" and episodenumber and seasonnumber tags; unfortunately the "new" tag seems to be pretty poorly implemented in the Sky data :(

I also added sessions and caching, also chunking for the Sky channels requests (the Sky EPG allows you to request 20 channels in one request), plus a few other changes that suited my use. Feel free to cherry-pick or ignore as you wish.

https://github.com/gwinkless/Freeview-EPG/commits/sky-awk/

**Comment by dp247** [comment]
@gwinkless never had a proper chance to say it but, thank you for this! I've been meaning to look into it for months, but I've added in the majority of your changes, so thanks a bunch!
