### ISSUE TITLE
[Channel+request]

### ISSUE THREAD

**Issue by vswee** [dp247/Freeview-EPG#34]
Please fill in the table:
> Note: If you're requesting a radio channel and/or a channel that airs on Freeview, please include your postcode in the additional information section.

|                                                       | Response              |
|--------------------------------------|-----------------------|
| Channel name                                | Gold    |
| Is the channel free-to-air?              | Yes              |
| Does the channel have a website? | https://gold.uktv.co.uk |
| Enter any additional information   | W14 8PU    |

**Comment by dp247** [comment]
Gold is not a free-to-air channel

**Comment by dp247** [comment]
Also thank you for your donation 😊
