### ISSUE TITLE
Various channels are missing

### ISSUE THREAD

**Issue by zanehed** [dp247/Freeview-EPG#37]
Using Jellyfin on Windows 11, postcode is PO4 Portsmouth from Rowridge transmitter

Missing BBC1, BBC2, ITV1, That's TV, BBC 4, QVC, Dave, BBC3, E4+1, ITV1+1, Sky Arts, QVC2, Challenge, Ideal World, Great movies, Blaze TCC, Earthx TV, Talking Pictures

![channels](https://github.com/dp247/Freeview-EPG/assets/111577322/ecc3c0ee-b1ec-4194-9c8b-c14a3eb5a8e4)

**Comment by zanehed** [comment]
Ok thanks, refreshed the guide, and here is the log file
[log_20240215.log](https://github.com/dp247/Freeview-EPG/files/14301431/log_20240215.log)

**Comment by dp247** [comment]
Yeah, so Jellyfin can see the channels in the file but can't match them to the M3U file you're using.

**Comment by zanehed** [comment]
Thanks for your time, Found where to remap the channels, and looking good.

**Comment by dp247** [comment]
Glad to hear it!
