### ISSUE TITLE
[Feature Request]Add guidance information

### ISSUE THREAD

**Issue by ExperiencersInternational** [dp247/Freeview-EPG#4]
Add XMLTV guidance information if that's possible for a specific program.

View how this could be used: https://github.com/XMLTV/xmltv/blob/master/xmltv.dtd

This could be an example of how it could be used:
```
<rating system="BBFC">
      <value>12</value>
      <icon src="12_symbol.png" />
    </rating>
```
Not entirely sure how to implement the content descriptors, e.g. 'mild swearing, violence'

**Comment by ExperiencersInternational** [comment]
Looking further, I'm guessing content descriptors aren't a thing? Seems kinda stupid to me ngl, since it would be more likely here to use a content descriptor rather than a rating.

![Screenshot_2023-04-17-22-16-04-103_com microsoft emmx](https://user-images.githubusercontent.com/56035537/232612698-5e50f438-8e5d-449f-a6f0-8ab814feec29.jpg)

**Comment by dp247** [comment]
Yeah, its one of those things that would definitely be nice to have, but like you've found, the nearest we'd get is the certification, and not even sure most sources have it :D
