### ISSUE TITLE
BBC non-HD channels missing

### ISSUE THREAD

**Issue by Dan-at-56** [dp247/Freeview-EPG#43]
Firstly, thanks for providing this.  It's really easy to use.

**Describe the issue**
I don't see the BBC non-HD channels such as BBC ONE Lon in the output.

**Expected behavior**
I expected all the channels to be listed, even if two channels have the same listings.

**Screenshots**
N/A.

**Device information**
Windows 10 PC;  Chrome browser, saving output to a text file and examining it using Notepad.  Also ingesting the output into Python and processing it for display in a wx GUI.

**Additional context**
Is this deliberate (ie. not an issue)?  Maybe it can be assumed that the listings for, say, BBC ONE Lon are the same as those for BBC ONE HD?  If that's so then please accept my apologies for raising a non-issue.

**Comment by dp247** [comment]
> Is this deliberate (ie. not an issue)?

Yes. BBC channels are pulled from Sky, which switched off SD services a couple of months ago. Since HD listings are identical to SD counterparts, I didn't see a need to source them from elsewhere (I only kept BBC Two really for ease of use)

**Comment by Dan-at-56** [comment]
Understood.  I will code around it.  Thanks for the prompt response.
