### ISSUE TITLE
[Issue]  Channel name appears corrupted: channel id="estHitsRadio.uk"

### ISSUE THREAD

**Issue by Dan-at-56** [dp247/Freeview-EPG#44]
**Describe the issue**
The channel name "estHitsRadio.uk" appears in the list - both in the channel entries list and in each of the programme entries for that channel.

**Expected behavior**
I suspect that it should be "GreatestHitsRadio.uk".

**Screenshots**
N/A.

**Device information**
Windows 10 PC; Chrome browser, saving to a file for examination with Notepad

**Additional context**
Search for instances of "estHitsRadio.uk" in the attached file (saved directly from Chrome).
[epg - orig.txt](https://github.com/dp247/Freeview-EPG/files/15099761/epg.-.orig.txt)

**Comment by dp247** [comment]
Thanks for the pointer! That's what happens when I use GitHub's find and replace on main branch 😆
