### ISSUE TITLE
Duplicate programme entries

### ISSUE THREAD

**Issue by Dan-at-56** [dp247/Freeview-EPG#45]
Describe the issue
For some programmes there seems to be 2 entries.  I've noticed this on channels including BBC ONE HD and 4Music - have not looked much further yet.

An example is that the following entry is repeated 
  <programme channel="4Music.uk" start="20240429000000 +0100" stop="20240429060000 +0100">
    <title lang="en">All The Hits, All Night</title>
    <desc lang="en">Non-stop hits to see you all the way through the night!</desc>
    <icon src="http://epgstatic.sky.com/epgdata/1.0/paimage/46/1/lisa/5.2.2/linear/channel/d3287fa4-c641-4eb8-b1c2-a6d6d77354db/1350"/>
  </programme>
  <programme channel="4Music.uk" start="20240429000000 +0100" stop="20240429060000 +0100">
    <title lang="en">All The Hits, All Night</title>
    <desc lang="en">Non-stop hits to see you all the way through the night!</desc>
    <icon src="http://epgstatic.sky.com/epgdata/1.0/paimage/46/1/lisa/5.2.2/linear/channel/d3287fa4-c641-4eb8-b1c2-a6d6d77354db/1350"/>
  </programme>

Sometimes the entry and its duplicate are consecutive in the output.  But I've also seen a block of duplicates following their originals.  Ie. Prog1, Prog2, Prog3, Prog4, Prog1, Prog2, Prog3, Prog4 

Expected behavior
Single entry for each programme

Screenshots
N/A.

Device information
Windows 10 PC; Chrome browser, saving to a file for examination with Notepad

Additional context
Search for instances of "All The Hits, All Night" in the attached file (saved directly from Chrome, then edited down to make the file a sensible size).
[epg.txt](https://github.com/dp247/Freeview-EPG/files/15139772/epg.txt)

**Comment by Dan-at-56** [comment]
Oh, apologies, the XML I pasted into the issue description has been rendered so you can't see the detail (ie. same start and stop dates/times for the two entries).  Best to look in the attachment as per the Additional context.

Cheers,
Dan

**Comment by dp247** [comment]
Looks like the duplicates are last in one day's data and also first in the next day's - since there's no checking for duplicates it just yeets them into the programme list.

**Comment by Dan-at-56** [comment]
Have a look at the data for BBCOneLondonHD from the last programme on the 27th ("Greta") through the next several hours in the attached (different) extract.  All seems fine for the following 20 or so entries up to start=20240428155000, but then it goes back and repeats everything from the last programme on the 27th, so that whole block of 20 or so entries is repeated.

Is this is a feature of the source from which you get the data?

For my use, I can deal with the dups easily enough - just have my fetch function check for a duplicate and, if so, don't include it in the output.  Would be nice to have this done at source or in your code but not important.

Cheers,
Dan

[epg2.txt](https://github.com/dp247/Freeview-EPG/files/15140205/epg2.txt)

**Comment by dp247** [comment]
> Is this is a feature of the source from which you get the data?

Probably not, most channels are sourced from Sky or Freeview

> Would be nice to have this done at source or in your code but not important.

I'll probably get round to it at some point, though I don't give timescales since this is a hobby. PRs are welcome though 😊

**Comment by Dan-at-56** [comment]
I updated to WG++ 5.3 and since then the problem has returned.  Do I need to replicate the change you made back in May?  If so, please let me know what I need to do.

Thanks,
Dan

**Comment by dp247** [comment]
> I updated to WG++ 5.3 and since then the problem has returned. Do I need to replicate the change you made back in May? If so, please let me know what I need to do.
> 
> Thanks, Dan

How strange, I can't see any issues with the file atm, but keep me posted if you do.

**Comment by Dan-at-56** [comment]
My profuse apologies - I posted my message to the wrong place.  The message relates to an issue with WebGrab++ and has nothing to do with your Freeview-EPG app.  Sorry for wasting your time.

**Comment by dp247** [comment]
Haha, don't worry about it 😊
