### ISSUE TITLE
Error with Libreelec/Kodi Simple IPTV 

### ISSUE THREAD

**Issue by webtaster** [dp247/Freeview-EPG#48]
When I plug the url into the configuration for the Simple IPTV plugin

https://raw.githubusercontent.com/dp247/Freeview-EPG/master/epg.xml

no EPG information is shown, and an error is generated in the log file (/storage/.kodi/temp/kodi.log):

error <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - LoadEPG - Unable parse EPG XML: Start-end tags mismatch, offset: 0:
                                                   [ display-name>     
                                                   ]

My setup: I am in the UK, running Libreelec 12.0 on a Raspberry Pi model 4.

**Expected behavior**
The file is read correctly and EPG information appears in the LibreElec EPG grid.

Cheers,
Jim

**Comment by dp247** [comment]
Think the process timed out, so closing

**Comment by portalbyte** [comment]
I also have the same issue, with it complaining about the start-end tags being mismatched and no EPG data is loaded.

**Comment by dp247** [comment]
> I also have the same issue, with it complaining about the start-end tags being mismatched and no EPG data is loaded.

Do you have a log file I could take a look at?
