### ISSUE TITLE
[Channel request] BBC Radio

### ISSUE THREAD

**Issue by ExperiencersInternational** [dp247/Freeview-EPG#5]
Doing some research and apparently Sky might have site IDs for certain BBC Radio channels but they don't actually show up

![microsoft_edge_screenshot_22 Apr 2023 17_32_48 BST png](https://user-images.githubusercontent.com/56035537/233796131-45256bdb-ae2a-4ce7-bfb4-e6f6a64e03e6.jpg)

I'm seeing if BT has any EPG assignments.

https://www.tvchannellists.com/w/Channels_testing_%26_channels_not_on_Sky%27s_EPG_(UK_%26_Ireland)

**Comment by ExperiencersInternational** [comment]
Found an old BBC page with zero leads as well

![microsoft_edge_screenshot_22 Apr 2023 18_29_06 BST png](https://user-images.githubusercontent.com/56035537/233798377-778a7911-3f9a-419d-9a3e-0919b0dc638b.jpg)

**Comment by dp247** [comment]
![image](https://user-images.githubusercontent.com/9065463/235008619-4f0c8c4a-4f6f-4e2e-8042-07bce59a4a68.png)

**Comment by dp247** [comment]
@ExperiencersInternational I'm away from my server atm, but I pushed a 48-hour EPG for the big BBC radio stations if you wanna try it (it only has radio stations and a Sky channel in):
```commandline
https://raw.githubusercontent.com/dp247/Freeview-EPG/radio/epg.xml
```
Might need to play around with some of the tvg-ids to get it working

**Comment by ExperiencersInternational** [comment]
Won't be able to test it rn thanks to my app supporting 4 EPGs, but only showing the first one

I'll try and see whether Live Channels + TVirl wants to work properly today instead of showing nothing

**Comment by dp247** [comment]
It mostly works:
![image](https://user-images.githubusercontent.com/9065463/235133996-36056da7-b0f3-49a3-8670-204251a59928.png)

There's an issue getting the last programme of the day (#6), but this is a step in the right direction at least

**Comment by ExperiencersInternational** [comment]
![image](https://user-images.githubusercontent.com/56035537/235251927-24191b15-f85e-4449-ba95-6e1160e83fc8.png)

Got it working, didn't realise config.m3u wasn't updated with the radio link. Also I'm not sure whether #6 is an issue lol

Would there be any chance whether we can merge the two EPGs eventually?

**Comment by ExperiencersInternational** [comment]
@dp247 sent a pull request for 719-x

**Comment by dp247** [comment]
> Would there be any chance whether we can merge the two EPGs eventually?

Yeah, I meant to do it today then got sidetracked :D
