### ISSUE TITLE
No fresh data

### ISSUE THREAD

**Issue by Dan-at-56** [dp247/Freeview-EPG#52]
I can't see any data for any time later than the early hours of tomorrow morning.  Is this something I'm doing wrong or is the feed not working?

I'm using Chrome on a Windows 10 PC.  I've saved the xml file and looked at the data in Notepad.

Thanks,
Dan

**Comment by dp247** [comment]
Thanks for pointing this out! Should be fixed now - it was something to do with a bug in NumPy, so I've locked down the requirements.

**Comment by Dan-at-56** [comment]
Yup - looks good from here.
      
      Thanks,
      Dan
      
      On 18/06/2024 23:48, David Park wrote:
    
    
      
      Thanks for pointing this out! Should be fixed now -
        it was something to do with a bug in NumPy, so I've locked down
        the requirements.
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        You are receiving this because you authored the thread.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/dp247/Freeview-EPG/issues/52#issuecomment-2177212100",
"url": "https://github.com/dp247/Freeview-EPG/issues/52#issuecomment-2177212100",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
