### ISSUE TITLE
[Channel request] ITV1 Granada

### ISSUE THREAD

**Issue by adam-rpyp** [dp247/Freeview-EPG#53]
You seem to have the "plus 1" version of this channel, ITV1Plus1Granada.uk, but not the normal one.

|                                                       | Response              |
|--------------------------------------|-----------------------|
| Channel name                                | ITV1 Granada |
| Is the channel free-to-air?              | Yes              |
| Does the channel have a website? | https://www.itv.com/ |
| Enter any additional information   | L16 3GL   |

**Comment by dp247** [comment]
For some reason, Sky uses ITV1 North as it's entry for Granada. I've added an ITV1 Granada since I couldn't possibly tell if it was correct or not lol.
