### ISSUE TITLE
Channel 4 data missing

### ISSUE THREAD

**Issue by Roquelobster** [dp247/Freeview-EPG#54]
**Describe the issue**
Channel 4 data is missing.  I just noticed it but it hasn't been populated for a while, my MythTV listing history only goes back 2 weeks and it's not there.  I can't see any listing content for Channel4.uk or Channel4Plus1.uk in the XML.

**Expected behavior**
Data is missing, can't schedule Big Fat Quiz on Dec 27!!!

**Comment by dp247** [comment]
Channel 4 +1 is fine, but C4 was broken, so should be fixed in the next run (alongside some other additions/deletions)

**Comment by Roquelobster** [comment]
Thanks C4 is no longer blank in the MythTV listings. Cheers and Merry Christmas!
